import React, { useEffect, useState } from "react"
import Navbar from "../navbar/Navbar"
import "./blogPost.css"
import { blog02 } from "../../containers/blog/imports"

const BlogTwo = () => {
  const getStoredComments = () => {
    const storedComments = localStorage.getItem("comments")
    return storedComments ? JSON.parse(storedComments) : []
  }

  const [comment, setComment] = useState("")
  const [comments, setComments] = useState(getStoredComments())

  const onClickHandler = () => {
    setComments((comments) => [...comments, comment])
  }

  const onChangeHandler = (e) => {
    setComment(e.target.value)
  }

  useEffect(() => {
    localStorage.setItem("comments", JSON.stringify(comments))
  }, [comments])

  return (
    <div className="gradient__bg">
      <Navbar />
      <div className="gpt4__blog section__padding ">
        <div className="">
          <h1 className="gradient__text">Ethics of AI Language Generation</h1>
          <p className="blog__date">March 13th, 2023</p>
          <p className="blog__content">
            Artificial intelligence (AI) language generation tools, such as the
            GPT-3 language model, have revolutionized the way we interact with
            text-based content. From generating creative writing to assisting
            with research, these tools have the potential to be highly useful in
            a variety of contexts. However, as with any technology, there are
            ethical considerations to be taken into account when it comes to AI
            language generation. <br />
          </p>
          <img
            className="blog__content-img"
            src={blog02}
            alt="Visual representation of binary code in the shape of a face"
          />
          <p className="blog__content">
            One of the primary ethical concerns with AI language generation is
            the potential for bias in the generated content. AI models like
            GPT-3 are trained on large datasets of text, and if those datasets
            contain biases - for example, stereotypes or discriminatory language
            - the AI may replicate those biases in its generated content. This
            could lead to harmful or offensive content being generated, which
            could have real-world consequences. <br />
            <br />
            To address this concern, it is important for developers to carefully
            curate the training data used to train AI language models, and to
            actively work to mitigate any biases that are present. This could
            involve using diverse datasets, incorporating human oversight into
            the training process, or using algorithms to identify and remove
            biased content. <br />
            <br />
            Another ethical concern with AI language generation is the potential
            for it to be used to spread false information or propaganda. As AI
            models become more advanced, it becomes increasingly difficult to
            discern between what is generated by an AI and what is created by a
            human. This could be exploited by bad actors to spread
            misinformation, sow discord, or otherwise manipulate public opinion.
            <br />
            <br /> To mitigate this risk, developers and users of AI language
            generation tools need to be mindful of the potential for misuse and
            work to develop safeguards to prevent it. This could involve
            incorporating fact-checking algorithms, incorporating human
            oversight or review, or implementing policies to prevent the use of
            AI-generated content for malicious purposes.
            <br />
            <br /> Privacy is another ethical concern with AI language
            generation. AI models like GPT-3 are trained on massive datasets of
            text, and some of that text may contain private or sensitive
            information. If an AI language model were to generate text that
            inadvertently revealed personal information, this could have serious
            consequences for individuals. <br />
            <br />
            To address this concern, it is important for developers to be
            transparent about what types of data are being used to train AI
            language models, and to incorporate safeguards to protect
            individuals' privacy. This could involve using anonymized or
            de-identified data, implementing data access controls, or
            implementing policies to prevent the use of AI-generated content
            that contains personal information. <br /> <br />
            In conclusion, while AI language generation tools like GPT-3 have
            the potential to be highly useful, there are ethical considerations
            that must be taken into account when developing and using these
            tools. Addressing concerns related to bias, misinformation, and
            privacy will be critical in ensuring that AI language generation is
            used responsibly and in a way that benefits society as a whole.
          </p>
        </div>
      </div>
      <div className="blog__comments-container ">
        {comments.map((text) => (
          <div className="blog__comments-display">
            <p className="blog__comments-display_user"> Anonymous</p>
            {text}
          </div>
        ))}

        <div className="blog__comments-content ">
          <h3 className="blog__comments-content-header gradient__text ">
            Leave a comment!
          </h3>
          <textarea
            value={comment}
            onChange={onChangeHandler}
            placeholder="Type your comment here..."
            className="blog__comments-content-input"
          />
          <button
            onClick={onClickHandler}
            className="blog__comments-content-button"
          >
            Submit
          </button>
        </div>
      </div>
    </div>
  )
}

export default BlogTwo
